# Pull the rosgzpx4 image
FROM ghcr.io/srindot/rosgzpx4:latest

# Grant ownership of the home directory to rosusr
USER root
RUN chown -R rosusr:rosusr /home/rosusr

# Set non-interactive mode for apt
ENV DEBIAN_FRONTEND=noninteractive

# Switch to bash shell
SHELL ["/bin/bash", "-c"]

WORKDIR /home/rosusr

# --- FIX START ---
# Refresh the expired ROS GPG Key before updating
RUN wget https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -O /usr/share/keyrings/ros-archive-keyring.gpg
# --- FIX END ---

# Update packages and install required dependencies
RUN apt-get update && apt-get install -y \
    ros-humble-ros-gzharmonic \
    python3-colcon-common-extensions && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install git+https://github.com/fishros/ros2bag_convert.git

RUN rm -rf /home/rosusr/PX4-Autopilot && \
    git clone https://github.com/pyromania99/PX4-Autopilot.git /home/rosusr/PX4-Autopilot && \
    cd /home/rosusr/PX4-Autopilot && \
    git submodule update --init --recursive
RUN chown -R rosusr:rosusr /home/rosusr/PX4-Autopilot

# Switch back to the non-root user 
USER rosusr

# Set the default command to open a bash shell
CMD ["bash"]